version: 2

jobs:
  test:
    docker:
      - image: cimg/ruby:2.6.6-node
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: ci_rails_sample_test
    working_directory: ~/myapp
    steps:
    - checkout
      - run:
          name: BundLER install
          command: |
            sudo gem update --system
            sudo gem install bundler -v 2.1.4
      - run:
          name: Bundle Update
          command: bundle update
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: wait for db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: set up for db
          command: bundle exec rake db:schema:load
      - run:
          name: rnu rspec
          command: bundle exec rspec

workflows:
  version: 2
  workflows:
    jobs:
      - test