version: 2
jobs:
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 10
      - run:
          name: rails db:create
          command: docker-compose run app rails db:create
      - run:
          name: rails db:migrate (skip db:seed)
          command: docker-compose run app rails db:migrate
      - run:
          name: rails db:test:prepare
          command: docker-compose run app rails db:test:prepare
      - run:
          name: rspec
          command: docker-compose run app rspec
      - run:
          name: docker-compose down
          command: docker-compose down

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      # - deploy:
      #     requires:
      #       - test
