default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
  port: 3306
  host: '127.0.0.1'
  database: ci_test
  password: password

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
# production:
#   <<: *default
#   database: myapp_production
#   username: myapp
#   password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
# production:
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   database: myapp_production
#   username: root
#   password:
#   socket: /var/lib/mysql/mysql.sock
